In [1]:
import pandas as pd

In [2]:
d={'id':[1,2,3,4,5,6,7,2,2,8],
    'name':['smith','allen','miller','martin','smith','scott','adams','allen','allen','king'],
    'dob':['01-jan-2002','01-jun-2002','31-jan-2002','15-aug-2002','01-jan-2003','01-feb-2003','15-aug-2002','01-jun-2002','01-jun-2002','01-jun-2000'],
    'place':['beng-560068','bengaluru-560068','beng-560011','chennai-600068','chen-600068','del-123445','delhi-123445','bengaluru-560068','bengaluru-560068','bengaluru-560077'],
    'score':[45,66,88,34,90,99,0,66,66,None],
    'stream':['BE-CS','BE-IS','BE-CS','BE-IS','BE-EEE','BCA','MCA','BE-IS','BE-IS',None],
    'unknown':[None]*10
 }
d

{'id': [1, 2, 3, 4, 5, 6, 7, 2, 2, 8],
 'name': ['smith',
  'allen',
  'miller',
  'martin',
  'smith',
  'scott',
  'adams',
  'allen',
  'allen',
  'king'],
 'dob': ['01-jan-2002',
  '01-jun-2002',
  '31-jan-2002',
  '15-aug-2002',
  '01-jan-2003',
  '01-feb-2003',
  '15-aug-2002',
  '01-jun-2002',
  '01-jun-2002',
  '01-jun-2000'],
 'place': ['beng-560068',
  'bengaluru-560068',
  'beng-560011',
  'chennai-600068',
  'chen-600068',
  'del-123445',
  'delhi-123445',
  'bengaluru-560068',
  'bengaluru-560068',
  'bengaluru-560077'],
 'score': [45, 66, 88, 34, 90, 99, 0, 66, 66, None],
 'stream': ['BE-CS',
  'BE-IS',
  'BE-CS',
  'BE-IS',
  'BE-EEE',
  'BCA',
  'MCA',
  'BE-IS',
  'BE-IS',
  None],
 'unknown': [None, None, None, None, None, None, None, None, None, None]}

In [3]:
pd.DataFrame(d)

   id    name          dob             place  score  stream unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS    None
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS    None
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS    None
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE    None
5   6   scott  01-feb-2003        del-123445   99.0     BCA    None
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA    None
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN    None

In [4]:
df = pd.DataFrame(d)

In [5]:
df

   id    name          dob             place  score  stream unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS    None
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS    None
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS    None
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE    None
5   6   scott  01-feb-2003        del-123445   99.0     BCA    None
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA    None
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS    None
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN    None

In [6]:
df.to_csv('student_details.csv',index=False)

In [7]:
df.to_excel('student_details.xlsx',index=False)  #install this in terminal ->pip install openpyxl

### **methods used in this file**:
1. DataFrame()
2. to_csv()
3. to_excel()