In [14]:
import pandas as pd

In [15]:
pd.read_csv('student_details.csv')

   id    name          dob             place  score  stream  unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445   99.0     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA      NaN
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN      NaN

In [16]:
df = pd.read_csv('student_details.csv')
df

   id    name          dob             place  score  stream  unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445   99.0     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA      NaN
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN      NaN

In [17]:
df.shape  #(rows,columns)

(10, 7)

In [18]:
df.columns  # returns list of column names

Index(['id', 'name', 'dob', 'place', 'score', 'stream', 'unknown'], dtype='str')

### 1. score,stream columns are having missing data.

### 2. unknown column is not important bcz it is completely missing values.

### 3. Score column data was typed in int and bcz of missing data it got converted as float.

In [19]:
df.info()  # info() is a method

#int and missing data cannot be togather

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       10 non-null     int64
 1   name     10 non-null     str
 2   dob      10 non-null     str
 3   place    10 non-null     str
 4   score    9 non-null      float64
 5   stream   9 non-null      str
 6   unknown  0 non-null      float64
dtypes: float64(2), int64(1), str(4)
memory usage: 692.0 bytes

In [20]:
df

   id    name          dob             place  score  stream  unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445   99.0     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA      NaN
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN      NaN

In [21]:
df['score']  # Accessing single column

0    45.0
1    66.0
2    88.0
3    34.0
4    90.0
5    99.0
6     0.0
7    66.0
8    66.0
9     NaN
Name: score, dtype: float64

In [22]:
df[['name','score']] # to select more than one column we need to use [[]] of column names

     name  score
0   smith   45.0
1   allen   66.0
2  miller   88.0
3  martin   34.0
4   smith   90.0
5   scott   99.0
6   adams    0.0
7   allen   66.0
8   allen   66.0
9    king    NaN

In [23]:
# Average of score column using mean()

score_mean = df['score'].mean()
score_mean

np.float64(61.55555555555556)

In [24]:
# df.fillna(score_mean)   # fillna -> detecting all the null value and replace with a mean (filling null values)

df['score'].fillna(score_mean)   # only for particular column missing values it is replacing with mean

0    45.000000
1    66.000000
2    88.000000
3    34.000000
4    90.000000
5    99.000000
6     0.000000
7    66.000000
8    66.000000
9    61.555556
Name: score, dtype: float64

In [25]:
df

   id    name          dob             place  score  stream  unknown
0   1   smith  01-jan-2002       beng-560068   45.0   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011   88.0   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068   34.0   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068   90.0  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445   99.0     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445    0.0     MCA      NaN
7   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
8   2   allen  01-jun-2002  bengaluru-560068   66.0   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077    NaN     NaN      NaN

In [26]:
df['score'] = df['score'].fillna(score_mean)

In [27]:
df

   id    name          dob             place      score  stream  unknown
0   1   smith  01-jan-2002       beng-560068  45.000000   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011  88.000000   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068  34.000000   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068  90.000000  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445  99.000000     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445   0.000000     MCA      NaN
7   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
8   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077  61.555556     NaN      NaN

# 01-09-2026

In [ ]:
# it shows how many duplicate values present in the data
df.duplicated().sum()  #all boolean values converted into 0's and 1's

np.int64(2)

In [36]:
df.duplicated().all()  #means no duplicate exist

np.False_

## **duplicated().any()** method is used to check if any one duplicate is present in table it generates o/p like this **np.True_** which means there exist a duplicate

In [35]:
df.duplicated().any()

np.False_

In [30]:
df.drop_duplicates(keep='last') # here last occurance it is keeping and remaining duplicates removes

   id    name          dob             place      score  stream  unknown
0   1   smith  01-jan-2002       beng-560068  45.000000   BE-CS      NaN
2   3  miller  31-jan-2002       beng-560011  88.000000   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068  34.000000   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068  90.000000  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445  99.000000     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445   0.000000     MCA      NaN
8   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
9   8    king  01-jun-2000  bengaluru-560077  61.555556     NaN      NaN

# we can keep the first occurance or last occurances not in middle data

In [33]:
#to remove the duplicates
df = df.drop_duplicates()
df  #by default first occurance is removing in name column we can i dentify allen name

   id    name          dob             place      score  stream  unknown
0   1   smith  01-jan-2002       beng-560068  45.000000   BE-CS      NaN
1   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
2   3  miller  31-jan-2002       beng-560011  88.000000   BE-CS      NaN
3   4  martin  15-aug-2002    chennai-600068  34.000000   BE-IS      NaN
4   5   smith  01-jan-2003       chen-600068  90.000000  BE-EEE      NaN
5   6   scott  01-feb-2003        del-123445  99.000000     BCA      NaN
6   7   adams  15-aug-2002      delhi-123445   0.000000     MCA      NaN
9   8    king  01-jun-2000  bengaluru-560077  61.555556     NaN      NaN

In [37]:
df.shape

(8, 7)

In [38]:
df['score']

0    45.000000
1    66.000000
2    88.000000
3    34.000000
4    90.000000
5    99.000000
6     0.000000
9    61.555556
Name: score, dtype: float64

In [ ]:
df

   id    name          dob             place      score  stream
0   1   smith  01-jan-2002       beng-560068  45.000000   BE-CS
1   2   allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS
2   3  miller  31-jan-2002       beng-560011  88.000000   BE-CS
3   4  martin  15-aug-2002    chennai-600068  34.000000   BE-IS
4   5   smith  01-jan-2003       chen-600068  90.000000  BE-EEE
5   6   scott  01-feb-2003        del-123445  99.000000     BCA
6   7   adams  15-aug-2002      delhi-123445   0.000000     MCA
9   8    king  01-jun-2000  bengaluru-560077  61.555556     NaN

In [39]:
df['name']

0     smith
1     allen
2    miller
3    martin
4     smith
5     scott
6     adams
9      king
Name: name, dtype: str

### directly we can't use str built in methods

In [40]:
df['name'].str.title()  # .str will go to every single string and it will convert return type is series of string

0     Smith
1     Allen
2    Miller
3    Martin
4     Smith
5     Scott
6     Adams
9      King
Name: name, dtype: str

In [41]:
df['name'].str.title()

0     Smith
1     Allen
2    Miller
3    Martin
4     Smith
5     Scott
6     Adams
9      King
Name: name, dtype: str

In [42]:
df['name'] = df['name'].str.title()

In [43]:
df

   id    name          dob             place      score  stream  unknown
0   1   Smith  01-jan-2002       beng-560068  45.000000   BE-CS      NaN
1   2   Allen  01-jun-2002  bengaluru-560068  66.000000   BE-IS      NaN
2   3  Miller  31-jan-2002       beng-560011  88.000000   BE-CS      NaN
3   4  Martin  15-aug-2002    chennai-600068  34.000000   BE-IS      NaN
4   5   Smith  01-jan-2003       chen-600068  90.000000  BE-EEE      NaN
5   6   Scott  01-feb-2003        del-123445  99.000000     BCA      NaN
6   7   Adams  15-aug-2002      delhi-123445   0.000000     MCA      NaN
9   8    King  01-jun-2000  bengaluru-560077  61.555556     NaN      NaN

### attributes(states/variable)
1.shape
2.columns

In [44]:
stream_mode = df['stream'].mode()[0]

In [45]:
df['stream'] = df['stream'].fillna(stream_mode)

fillna() is used to add the values in missing data

In [46]:
df['place']

0         beng-560068
1    bengaluru-560068
2         beng-560011
3      chennai-600068
4         chen-600068
5          del-123445
6        delhi-123445
9    bengaluru-560077
Name: place, dtype: str

In [47]:
# split() ->to convert string into list
df[['place','pincode']] = df['place'].str.split('-',expand=True)

In [48]:
df

   id    name          dob      place      score  stream  unknown pincode
0   1   Smith  01-jan-2002       beng  45.000000   BE-CS      NaN  560068
1   2   Allen  01-jun-2002  bengaluru  66.000000   BE-IS      NaN  560068
2   3  Miller  31-jan-2002       beng  88.000000   BE-CS      NaN  560011
3   4  Martin  15-aug-2002    chennai  34.000000   BE-IS      NaN  600068
4   5   Smith  01-jan-2003       chen  90.000000  BE-EEE      NaN  600068
5   6   Scott  01-feb-2003        del  99.000000     BCA      NaN  123445
6   7   Adams  15-aug-2002      delhi   0.000000     MCA      NaN  123445
9   8    King  01-jun-2000  bengaluru  61.555556   BE-CS      NaN  560077

In [49]:
d={'beng':'bengaluru','chen':'chennai','del':'delhi'}
df['place'] = df['place'].replace(d)

In [50]:
df

   id    name          dob      place      score  stream  unknown pincode
0   1   Smith  01-jan-2002  bengaluru  45.000000   BE-CS      NaN  560068
1   2   Allen  01-jun-2002  bengaluru  66.000000   BE-IS      NaN  560068
2   3  Miller  31-jan-2002  bengaluru  88.000000   BE-CS      NaN  560011
3   4  Martin  15-aug-2002    chennai  34.000000   BE-IS      NaN  600068
4   5   Smith  01-jan-2003    chennai  90.000000  BE-EEE      NaN  600068
5   6   Scott  01-feb-2003      delhi  99.000000     BCA      NaN  123445
6   7   Adams  15-aug-2002      delhi   0.000000     MCA      NaN  123445
9   8    King  01-jun-2000  bengaluru  61.555556   BE-CS      NaN  560077

In [54]:
df = df.drop(columns='unknown')

In [55]:
df

   id    name          dob      place      score  stream pincode
0   1   Smith  01-jan-2002  bengaluru  45.000000   BE-CS  560068
1   2   Allen  01-jun-2002  bengaluru  66.000000   BE-IS  560068
2   3  Miller  31-jan-2002  bengaluru  88.000000   BE-CS  560011
3   4  Martin  15-aug-2002    chennai  34.000000   BE-IS  600068
4   5   Smith  01-jan-2003    chennai  90.000000  BE-EEE  600068
5   6   Scott  01-feb-2003      delhi  99.000000     BCA  123445
6   7   Adams  15-aug-2002      delhi   0.000000     MCA  123445
9   8    King  01-jun-2000  bengaluru  61.555556   BE-CS  560077

### **Methods used in this file till now**
1. read_csv() -> supports to read only csv files
2. mean()
3. info()
4. fillna()
5. duplicated()
6. sum()
7. any()
8. drop_duplicates()
9. str.title()
10. duplicated().all()
11. astype()
12. drop(columns=[])
13. duplicated().any()
14. duplicated().sum()
15. mode()
16. str.split()
17. replace()

In [51]:
df['place']

0    bengaluru
1    bengaluru
2    bengaluru
3      chennai
4      chennai
5        delhi
6        delhi
9    bengaluru
Name: place, dtype: str

In [56]:
s = df['place'].value_counts()
d = dict(s)
d

{'bengaluru': np.int64(4), 'chennai': np.int64(2), 'delhi': np.int64(2)}