## titanic data analysis

# 1. load and understand the dataset

In [340]:
import pandas as pd

In [341]:
#load the dataset and understand the dataset
df = pd.read_csv('titanic.csv')

# 2. clean the dataset
1. check for duplicates and remove them.
2. check for missing values and handle them/ remove them.
3. check for invalid datatypes and handle them.
4. remove any unnecessary columns.

In [342]:
df.columns # columns is a attribute used to see the column names

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='str')

pclass --->passenger class

sibsp --->siblings and  spouse count

parch--->parent and chidren count

embarked --->port name

fare--->amount

In [343]:
# head() -> generates first 5 rows data
df.head(5)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [344]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    str
 9   embarked  1307 non-null   str
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 112.6 KB

Columns are having missing values ->
1. age
2. fare
3. cabin
4. embarked

In [345]:
#step 1:
df.duplicated().any() #np.False_ --> no duplicates exist

np.False_

In [346]:
#step 2:
#to check missing values togather at once using loop
for col in ['age','fare','cabin','embarked']:
    print(col,df[col].isnull().sum(),sep='-->')  # np.int64(263) here 263 are missing

age-->263
fare-->1
cabin-->1014
embarked-->2

In [347]:
age_mean = df['age'].mean()
df['age'] = df['age'].fillna(age_mean)

In [348]:
fare_mean = df['fare'].mean()
df['fare'] = df['fare'].fillna(fare_mean)

In [349]:
df['embarked'].mode()  # 0    S  it is a series

0    S
Name: embarked, dtype: str

In [350]:
df['embarked'].mode()[0] # 'S' now its a string

'S'

In [351]:
embarked_mode = df['embarked'].mode()[0]
df['embarked'] = df['embarked'].fillna(embarked_mode)

In [352]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1309 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1309 non-null   float64
 8   cabin     295 non-null    str
 9   embarked  1309 non-null   str
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 112.6 KB

In [353]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,NaN,S,0

In [354]:
# check for columns which are having missing values and remove them 
#axis=0 indicates rows  #axis=1 indicates columns
df = df.dropna(axis=1)

In [355]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,S,0
...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,S,0

df.info()

In [356]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1309 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1309 non-null   float64
 8   embarked  1309 non-null   str
 9   survived  1309 non-null   int64
dtypes: float64(2), int64(4), str(4)
memory usage: 102.4 KB

In [357]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,S,0
...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,S,0

# 04-09-2026

# 3. Transform the dataset (Data Manipulation or Data Transformation)

In [358]:
# family count(sibsp+parch) using "+" operator
df['family_count'] = df['sibsp'] + df['parch']

In [359]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,S,1,0
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,S,1,3
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,S,0,3
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,S,0,3
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,S,0,3
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,C,0,1
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,C,0,1
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,C,0,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,C,0,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,S,0,0

In [360]:
#unique and distinct values in particular column
df['ticket'].unique()

<StringArray>
[     '24160',     '113781',      '19952',      '13502',     '112050',
      '11769',   'PC 17609',   'PC 17757',   'PC 17477',      '19877',
 ...
     '315154', 'A/4. 34244',     '345771',       '2659',       '2628',
       '2647',       '2665',       '2656',       '2670',     '315082']
Length: 929, dtype: str

In [361]:
# sort_values --> values called as columns
df = df.sort_values(by='ticket')  # here sorting happen by ascii values

In [362]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count
67,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,S,1,0
245,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,S,1,0
195,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,S,1,0
289,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.650,S,1,2
291,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,S,1,2
...,...,...,...,...,...,...,...,...,...,...,...
63,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.175,S,1,1
62,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,S,0,1
433,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,S,0,0
81,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,S,0,2
82,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,S,1,2

In [363]:
# df = df.reset_index()
df = df.reset_index(drop=True)  # to remove old index we (drop=true)

In [364]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,S,1,0
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,S,1,0
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,S,1,0
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.650,S,1,2
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,S,1,2
...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.175,S,1,1
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,S,0,1
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,S,0,0
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,S,0,2
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,S,1,2

In [365]:
df['embarked'].unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [366]:
df['embarked'] = df['embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstwon'})

In [367]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,Southampton,1,0
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,Southampton,1,0
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,Southampton,1,0
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.650,Southampton,1,2
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,Southampton,1,2
...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.175,Southampton,1,1
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,Southampton,0,1
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,Southampton,0,0
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,Southampton,0,2
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,Southampton,1,2

In [368]:
df['fare']

0       86.500
1       86.500
2       86.500
3       79.650
4       79.650
         ...
1304    61.175
1305    61.175
1306    10.500
1307    71.000
1308    71.000
Name: fare, Length: 1309, dtype: float64

In [369]:
df['fare'] = df['fare'].round(1)

In [370]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,Southampton,1,0
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5,Southampton,1,0
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5,Southampton,1,0
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.6,Southampton,1,2
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6,Southampton,1,2
...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5,Southampton,0,0
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2

In [371]:
df[['last_name','temp_name']] = df['name'].str.split(',',expand=True)  # expand-true list is covert as a dataframe

In [372]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,temp_name
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss. Gladys
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess. of (Lucy Noel Martha Dyer-Edwards)
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss. Roberta
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss. Ruth
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs. Emil (Tillie Mandelbaum)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs. Herbert Fuller (Carrie Constance Toogood)
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr. Herbert Fuller
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr. Walter
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt. Edward Gifford
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss. Harriet R

In [373]:
 # '.' can be more than one in a name , here we take one '.' for spliting
df[['title','first_name']] = df['temp_name'].str.split('.',n=1,expand=True)  # n=1 means from the left side we have to make split where the dot is present

In [374]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,temp_name,title,first_name
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss. Gladys,Miss,Gladys
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess. of (Lucy Noel Martha Dyer-Edwards),the Countess,of (Lucy Noel Martha Dyer-Edwards)
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss. Roberta,Miss,Roberta
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss. Ruth,Miss,Ruth
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs. Emil (Tillie Mandelbaum),Mrs,Emil (Tillie Mandelbaum)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs. Herbert Fuller (Carrie Constance Toogood),Mrs,Herbert Fuller (Carrie Constance Toogood)
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr. Herbert Fuller,Mr,Herbert Fuller
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr. Walter,Mr,Walter
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt. Edward Gifford,Capt,Edward Gifford
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss. Harriet R,Miss,Harriet R

# 05-09-2026

In [375]:
df['title'].str.strip()    #whenever we use split() ,it mandatory to use strip()

0               Miss
1       the Countess
2               Miss
3               Miss
4                Mrs
            ...
1304             Mrs
1305              Mr
1306              Mr
1307            Capt
1308            Miss
Name: title, Length: 1309, dtype: str

In [376]:
for col in ['title','first_name','last_name']:
    df[col] = df[col].str.strip()

In [377]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,temp_name,title,first_name
0,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss. Gladys,Miss,Gladys
1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess. of (Lucy Noel Martha Dyer-Edwards),the Countess,of (Lucy Noel Martha Dyer-Edwards)
2,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss. Roberta,Miss,Roberta
3,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss. Ruth,Miss,Ruth
4,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs. Emil (Tillie Mandelbaum),Mrs,Emil (Tillie Mandelbaum)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs. Herbert Fuller (Carrie Constance Toogood),Mrs,Herbert Fuller (Carrie Constance Toogood)
1305,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr. Herbert Fuller,Mr,Herbert Fuller
1306,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr. Walter,Mr,Walter
1307,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt. Edward Gifford,Capt,Edward Gifford
1308,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss. Harriet R,Miss,Harriet R

In [378]:
df = df.drop(columns=['name','temp_name'])

In [379]:
df

,pclass,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,title,first_name
0,1,female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss,Gladys
1,1,female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess,of (Lucy Noel Martha Dyer-Edwards)
2,1,female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss,Roberta
3,1,female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss,Ruth
4,1,female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs,Emil (Tillie Mandelbaum)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood)
1305,1,male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr,Herbert Fuller
1306,2,male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr,Walter
1307,1,male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt,Edward Gifford
1308,1,female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss,Harriet R

In [380]:
df['sex'] = df['sex'].str.title()

In [381]:
df

,pclass,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,title,first_name
0,1,Female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss,Gladys
1,1,Female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess,of (Lucy Noel Martha Dyer-Edwards)
2,1,Female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss,Roberta
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss,Ruth
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs,Emil (Tillie Mandelbaum)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood)
1305,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr,Herbert Fuller
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr,Walter
1307,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt,Edward Gifford
1308,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss,Harriet R

In [382]:
df['ticket']

0            110152
1            110152
2            110152
3            110413
4            110413
           ...
1304    W.E.P. 5734
1305    W.E.P. 5734
1306      W/C 14208
1307      WE/P 5735
1308      WE/P 5735
Name: ticket, Length: 1309, dtype: str

# **value_counts()** method which will will group and count one after the other

In [383]:
df['ticket'].value_counts() #returns Series  (Occurance of each ticket)
# here index --> ticket data
# values ---> count of each ticket

ticket
CA. 2343       11
1601            8
CA 2144         8
3101295         7
347077          7
               ..
W./C. 14260     1
W./C. 14263     1
W./C. 14266     1
W./C. 6609      1
W/C 14208       1
Name: count, Length: 929, dtype: int64

In [384]:
# Here we are converting series to dictionary
s = (df['ticket'].value_counts())
d = dict(s)

In [385]:
df['passengers_count'] = df['ticket'].map(d)

In [386]:
df

,pclass,sex,age,sibsp,parch,ticket,fare,embarked,survived,family_count,last_name,title,first_name,passengers_count
0,1,Female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss,Gladys,3
1,1,Female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess,of (Lucy Noel Martha Dyer-Edwards),3
2,1,Female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss,Roberta,3
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss,Ruth,3
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs,Emil (Tillie Mandelbaum),3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood),2
1305,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr,Herbert Fuller,2
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr,Walter,1
1307,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt,Edward Gifford,2
1308,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss,Harriet R,2

In [387]:
df['sex']

0       Female
1       Female
2       Female
3       Female
4       Female
         ...
1304    Female
1305      Male
1306      Male
1307      Male
1308    Female
Name: sex, Length: 1309, dtype: str

# 07-09-2026

In [388]:
# Reamne the column
df = df.rename(columns = {'sex':'Gender','embarked':'Port'})

In [389]:
df

,pclass,Gender,age,sibsp,parch,ticket,fare,Port,survived,family_count,last_name,title,first_name,passengers_count
0,1,Female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss,Gladys,3
1,1,Female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess,of (Lucy Noel Martha Dyer-Edwards),3
2,1,Female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss,Roberta,3
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss,Ruth,3
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs,Emil (Tillie Mandelbaum),3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood),2
1305,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr,Herbert Fuller,2
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr,Walter,1
1307,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt,Edward Gifford,2
1308,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss,Harriet R,2

In [390]:
def companion_type_function(row):
    f=row['family_count']    #holds one value (single cell value)
    p=row['passengers_count']
    if p == 1:
        return 'solo'
    else:
        if f==0:
            return 'friends'
        else:
            return 'family'

## **apply()** is a method which acts like a intermediatary , it will go to dataframe and gives to function

In [391]:
df['companion_type'] = df.apply(companion_type_function,axis=1)  # axis=1 means select all columns of 1st row,2nd row, .........., nth row)

In [392]:
df

,pclass,Gender,age,sibsp,parch,ticket,fare,Port,survived,family_count,last_name,title,first_name,passengers_count,companion_type
0,1,Female,30.0,0,0,110152,86.5,Southampton,1,0,Cherry,Miss,Gladys,3,friends
1,1,Female,33.0,0,0,110152,86.5,Southampton,1,0,Rothes,the Countess,of (Lucy Noel Martha Dyer-Edwards),3,friends
2,1,Female,16.0,0,0,110152,86.5,Southampton,1,0,Maioni,Miss,Roberta,3,friends
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,2,Taussig,Miss,Ruth,3,family
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,2,Taussig,Mrs,Emil (Tillie Mandelbaum),3,family
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,1,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood),2,family
1305,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,1,Chaffee,Mr,Herbert Fuller,2,family
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,0,Harris,Mr,Walter,1,solo
1307,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,2,Crosby,Capt,Edward Gifford,2,family
1308,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,2,Crosby,Miss,Harriet R,2,family

In [393]:
df.columns

Index(['pclass', 'Gender', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'Port',
       'survived', 'family_count', 'last_name', 'title', 'first_name',
       'passengers_count', 'companion_type'],
      dtype='str')

In [394]:
new_col_order = ['ticket','title', 'first_name','last_name','Gender', 'age','companion_type','Port','pclass','fare','survived']

In [395]:
df = df[new_col_order]

In [396]:
df

,ticket,title,first_name,last_name,Gender,age,companion_type,Port,pclass,fare,survived
0,110152,Miss,Gladys,Cherry,Female,30.0,friends,Southampton,1,86.5,1
1,110152,the Countess,of (Lucy Noel Martha Dyer-Edwards),Rothes,Female,33.0,friends,Southampton,1,86.5,1
2,110152,Miss,Roberta,Maioni,Female,16.0,friends,Southampton,1,86.5,1
3,110413,Miss,Ruth,Taussig,Female,18.0,family,Southampton,1,79.6,1
4,110413,Mrs,Emil (Tillie Mandelbaum),Taussig,Female,39.0,family,Southampton,1,79.6,1
...,...,...,...,...,...,...,...,...,...,...,...
1304,W.E.P. 5734,Mrs,Herbert Fuller (Carrie Constance Toogood),Chaffee,Female,47.0,family,Southampton,1,61.2,1
1305,W.E.P. 5734,Mr,Herbert Fuller,Chaffee,Male,46.0,family,Southampton,1,61.2,0
1306,W/C 14208,Mr,Walter,Harris,Male,30.0,solo,Southampton,2,10.5,0
1307,WE/P 5735,Capt,Edward Gifford,Crosby,Male,70.0,family,Southampton,1,71.0,0
1308,WE/P 5735,Miss,Harriet R,Crosby,Female,36.0,family,Southampton,1,71.0,1

### 4. Data Analysis
1. using pandas 
2. using visuals